from enum import StrEnum


class ErrorCode(StrEnum):
    UNAUTHORIZE = "UNAUTHORIZE"
    FORBIDDEN = "FORBIDDEN"

    STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
    STUDENT_ALREADY_EXISTS = "STUDENT_ALREADY_EXISTS"

    NOT_FOUND = "NOT_FOUND"
